language: python

jobs:
  include:
    - stage: pages
      install:
        - pip install click colorama colorclass future "sphinx==1.8.5" sphinxcontrib-bibtex sphinx_rtd_theme
        - pip install https://github.com/H0R5E/sphinxcontrib-versioning/archive/v1.8.5_support.zip
        - pip install git+https://github.com/H0R5E/matlabdomain.git/@function_arguments#egg=matlabdomain
      script:
        - eval "$(ssh-agent -s)"; touch .travis/key; chmod 0600 .travis/key
        - openssl aes-256-cbc -d -K $encrypted_c97e05834f48_key -iv $encrypted_c97e05834f48_iv < .travis/key.enc > .travis/key
          && ssh-add .travis/key  # Use && to prevent ssh-add from prompting during pull requests.
        - git config --global user.email "builds@travis-ci.com"
        - git config --global user.name "Travis CI"
        - git remote set-url --push origin "git@github.com:$TRAVIS_REPO_SLUG"
        - sphinx-versioning push -abt -e .nojekyll -e README.md docs gh-pages .
      if: branch = master AND (type = push OR tag IS present)
